#!/bin/sh

set -e

TEAM_NUMBER="$1"
NAO_NUMBER="$2"

echo "[Match]
Name=wlan*

[Network]
Address=10.0.${TEAM_NUMBER}.${NAO_NUMBER}/16

[Route]
Gateway=0.0.0.0
" > /etc/systemd/network/80-wlan.network

echo "[Match]
Name=en* eth*

[Network]
Address=10.1.${TEAM_NUMBER}.${NAO_NUMBER}/16

[Route]
Gateway=0.0.0.0
" > /etc/systemd/network/80-wired.network

hostnamectl set-hostname ${HOSTNAME}

systemctl restart systemd-networkd
